"""Change content fields to LONGTEXT for large data support

Revision ID: 94b253ab1d17
Revises: 9adebfd25fab
Create Date: 2025-11-21 22:06:20.340876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94b253ab1d17'
down_revision: Union[str, None] = '9adebfd25fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('article_section', 'content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_comment='处理后的内容（纯文本）',
               existing_nullable=False)
    op.alter_column('article_section', 'raw_content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_comment='原始内容（可能包含markdown/html）',
               existing_nullable=True)
    op.alter_column('chat_message', 'content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('source_chunk', 'content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('source_chunk', 'raw_content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('source_event', 'summary',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('source_event', 'content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_event', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('source_event', 'summary',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('source_chunk', 'raw_content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('source_chunk', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('chat_message', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('article_section', 'raw_content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_comment='原始内容（可能包含markdown/html）',
               existing_nullable=True)
    op.alter_column('article_section', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_comment='处理后的内容（纯文本）',
               existing_nullable=False)
    op.alter_column('article', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
