"""sync article_section fields

Revision ID: 9adebfd25fab
Revises: 865837abd4b7
Create Date: 2025-11-17 16:38:38.149020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9adebfd25fab'
down_revision: Union[str, None] = '865837abd4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_section', sa.Column('order_index', sa.Integer(), nullable=False, comment='排序索引'))
    op.add_column('article_section', sa.Column('type', sa.String(length=50), nullable=True, comment='片段类型：TEXT/IMAGE/CODE/TABLE等'))
    op.add_column('article_section', sa.Column('raw_content', sa.Text(), nullable=True, comment='原始内容（可能包含markdown/html）'))
    op.add_column('article_section', sa.Column('image_url', sa.String(length=500), nullable=True, comment='图片URL（仅图片类型）'))
    op.add_column('article_section', sa.Column('length', sa.Integer(), nullable=False, comment='内容长度'))
    op.alter_column('article_section', 'content',
               existing_type=mysql.TEXT(),
               comment='处理后的内容（纯文本）',
               existing_nullable=False)
    op.create_index('idx_article_order', 'article_section', ['article_id', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_article_order', table_name='article_section')
    op.alter_column('article_section', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='处理后的内容（纯文本）',
               existing_nullable=False)
    op.drop_column('article_section', 'length')
    op.drop_column('article_section', 'image_url')
    op.drop_column('article_section', 'raw_content')
    op.drop_column('article_section', 'type')
    op.drop_column('article_section', 'order_index')
    # ### end Alembic commands ###
